[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/"},
    { access = "read", path = "./deployments"},
    { access = "read", path = "./out"}
]
evm_version = "cancun"
auto_detect_solc = true
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
script_execution_protection = false

[profile.permit2]
solc = "0.8.17"
src = "lib/permit2/src"

[profile.local]
eth_rpc_url = "http://localhost:8545"

[rpc_endpoints]
local = "http://localhost:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config