[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
evm_version = "cancun"
auto_detect_solc = true
solc_version = "0.8.26"
auto_detect_remappings = false
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.permit2]
solc = "0.8.17"
src = "lib/permit2/src"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config